spring.application.name=spring-board
spring.devtools.livereload.enabled=true
#TRACE DEBUG INFO WARN ERROR
logging.level.net.likelion.bebc25=DEBUG

## JDBC 설정
spring.datasource.url=jdbc:mysql://localhost:3306/board_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=003098pp

spring.sql.init.mode=always